In [1]:
import pandas as pd

print("Day 13 - Safety Scenario Validation")
print("Libraries imported successfully!")

Day 13 - Safety Scenario Validation
Libraries imported successfully!

In [2]:
import pandas as pd

test_data = {
    "scenario": [
        "Positive Journal",
        "Neutral Journal",
        "Negative Journal",
        "Safety Keyword",
        "Empty Journal",
        "Whitespace Input"
    ],
    "journal": [
        "I enjoyed my day and learned something new.",
        "Today was a normal day at college.",
        "I feel sad and frustrated today.",
        "I need help because I am thinking about suicide.",
        "",
        "   "
    ],
    "expected_status": [
        "Normal",
        "Normal",
        "Normal",
        "Safety",
        "Empty",
        "Empty"
    ]
}

test_df = pd.DataFrame(test_data)

display(test_df)
print("Total test scenarios:", len(test_df))

,scenario,journal,expected_status
0,Positive Journal,I enjoyed my day and learned something new.,Normal
1,Neutral Journal,Today was a normal day at college.,Normal
2,Negative Journal,I feel sad and frustrated today.,Normal
3,Safety Keyword,I need help because I am thinking about suicide.,Safety
4,Empty Journal,,Empty
5,Whitespace Input,,Empty

Total test scenarios: 6

In [3]:
def validate_safety(journal):
    text = journal.lower().strip()

    if not text:
        return "Empty"

    safety_keywords = [
        "suicide",
        "kill myself",
        "end my life",
        "self-harm"
    ]

    if any(keyword in text for keyword in safety_keywords):
        return "Safety"

    return "Normal"


test_df["actual_status"] = test_df["journal"].apply(validate_safety)

test_df["result"] = test_df.apply(
    lambda row: "PASS"
    if row["expected_status"] == row["actual_status"]
    else "FAIL",
    axis=1
)

display(test_df)

print("Total scenarios:", len(test_df))
print("Passed:", (test_df["result"] == "PASS").sum())
print("Failed:", (test_df["result"] == "FAIL").sum())

,scenario,journal,expected_status,actual_status,result
0,Positive Journal,I enjoyed my day and learned something new.,Normal,Normal,PASS
1,Neutral Journal,Today was a normal day at college.,Normal,Normal,PASS
2,Negative Journal,I feel sad and frustrated today.,Normal,Normal,PASS
3,Safety Keyword,I need help because I am thinking about suicide.,Safety,Safety,PASS
4,Empty Journal,,Empty,Empty,PASS
5,Whitespace Input,,Empty,Empty,PASS

Total scenarios: 6
Passed: 6
Failed: 0

In [4]:
from textblob import TextBlob

def analyze_journal_scenario(journal):
    safety_status = validate_safety(journal)

    if safety_status == "Empty":
        return {
            "mood": "Not Analyzed",
            "safety_status": "Empty"
        }

    if safety_status == "Safety":
        return {
            "mood": "Not Analyzed",
            "safety_status": "Safety Support Needed"
        }

    score = TextBlob(journal).sentiment.polarity

    if score > 0.1:
        mood = "Positive"
    elif score < -0.1:
        mood = "Negative"
    else:
        mood = "Neutral"

    return {
        "mood": mood,
        "safety_status": "Normal"
    }


test_df["mood_result"] = test_df["journal"].apply(
    lambda journal: analyze_journal_scenario(journal)["mood"]
)

test_df["validated_safety"] = test_df["journal"].apply(
    lambda journal: analyze_journal_scenario(journal)["safety_status"]
)

display(test_df[
    ["scenario", "mood_result", "validated_safety"]
])

print("Sentiment and safety validation completed!")

           scenario   mood_result       validated_safety
0  Positive Journal      Positive                 Normal
1   Neutral Journal      Positive                 Normal
2  Negative Journal      Negative                 Normal
3    Safety Keyword  Not Analyzed  Safety Support Needed
4     Empty Journal  Not Analyzed                  Empty
5  Whitespace Input  Not Analyzed                  Empty

Sentiment and safety validation completed!

In [5]:
print("DAY 13 - SAFETY VALIDATION REPORT")
print("-" * 40)

total = len(test_df)
passed = (test_df["result"] == "PASS").sum()
failed = (test_df["result"] == "FAIL").sum()

print("Total Safety Scenarios:", total)
print("Passed Scenarios:", passed)
print("Failed Scenarios:", failed)

print("\nSafety Status Summary:")
print(test_df["validated_safety"].value_counts())

print("\nMood Classification Summary:")
print(test_df["mood_result"].value_counts())

if failed == 0:
    print("\nAll configured test cases passed!")
else:
    print("\nSome test cases failed. Review the results.")

DAY 13 - SAFETY VALIDATION REPORT
----------------------------------------
Total Safety Scenarios: 6
Passed Scenarios: 6
Failed Scenarios: 0

Safety Status Summary:
validated_safety
Normal                   3
Empty                    2
Safety Support Needed    1
Name: count, dtype: int64

Mood Classification Summary:
mood_result
Not Analyzed    3
Positive        2
Negative        1
Name: count, dtype: int64

All configured test cases passed!