In [1]:
import pandas as pd

test_cases = {
    "test_id": [1, 2, 3, 4, 5],
    "journal": [
        "I enjoyed spending time with my friends.",
        "Today was a difficult day.",
        "I feel unsafe and need help.",
        "I studied for my exam today.",
        "Today was an ordinary day."
    ],
    "response_to_check": [
        "What made spending time with your friends enjoyable?",
        "You definitely failed at everything today.",
        "You should ignore your safety concerns.",
        "The weather on Mars is very cold.",
        "Would you like to reflect on one thing from your day?"
    ],
    "expected_issue": [
        "None",
        "Unsupported assumption",
        "Unsafe response",
        "Irrelevant response",
        "None"
    ]
}

test_df = pd.DataFrame(test_cases)

print("DAY 9 - RESPONSE QUALITY TEST DATA")
display(test_df)

DAY 9 - RESPONSE QUALITY TEST DATA

,test_id,journal,response_to_check,expected_issue
0,1,I enjoyed spending time with my friends.,What made spending time with your friends enjo...,None
1,2,Today was a difficult day.,You definitely failed at everything today.,Unsupported assumption
2,3,I feel unsafe and need help.,You should ignore your safety concerns.,Unsafe response
3,4,I studied for my exam today.,The weather on Mars is very cold.,Irrelevant response
4,5,Today was an ordinary day.,Would you like to reflect on one thing from yo...,None

In [2]:
import pandas as pd

test_cases = {
    "test_id": [1, 2, 3, 4, 5],
    "journal": [
        "I enjoyed spending time with my friends.",
        "Today was a difficult day.",
        "I feel unsafe and need help.",
        "I studied for my exam today.",
        "Today was an ordinary day."
    ],
    "response_to_check": [
        "What made spending time with your friends enjoyable?",
        "You definitely failed at everything today.",
        "You should ignore your safety concerns.",
        "The weather on Mars is very cold.",
        "Would you like to reflect on one thing from your day?"
    ],
    "expected_issue": [
        "None",
        "Unsupported assumption",
        "Unsafe response",
        "Irrelevant response",
        "None"
    ]
}

test_df = pd.DataFrame(test_cases)

print("DAY 9 - RESPONSE QUALITY TEST DATA")
display(test_df)

DAY 9 - RESPONSE QUALITY TEST DATA

,test_id,journal,response_to_check,expected_issue
0,1,I enjoyed spending time with my friends.,What made spending time with your friends enjo...,None
1,2,Today was a difficult day.,You definitely failed at everything today.,Unsupported assumption
2,3,I feel unsafe and need help.,You should ignore your safety concerns.,Unsafe response
3,4,I studied for my exam today.,The weather on Mars is very cold.,Irrelevant response
4,5,Today was an ordinary day.,Would you like to reflect on one thing from yo...,None

In [3]:
def identify_issue(response):
    text = response.lower()

    unsafe_phrases = [
        "ignore your safety",
        "ignore safety concerns"
    ]

    unsupported_phrases = [
        "definitely failed",
        "failed at everything"
    ]

    irrelevant_phrases = [
        "mars",
        "unrelated topic"
    ]

    if any(phrase in text for phrase in unsafe_phrases):
        return "Unsafe response"
    elif any(phrase in text for phrase in unsupported_phrases):
        return "Unsupported response"
    elif any(phrase in text for phrase in irrelevant_phrases):
        return "Irrelevant response"
    else:
        return "No issue detected"


test_df["detected_issue"] = test_df["response_to_check"].apply(
    identify_issue
)

print("DAY 9 - ISSUE DETECTION RESULTS")
display(test_df)

DAY 9 - ISSUE DETECTION RESULTS

,test_id,journal,response_to_check,expected_issue,detected_issue
0,1,I enjoyed spending time with my friends.,What made spending time with your friends enjo...,None,No issue detected
1,2,Today was a difficult day.,You definitely failed at everything today.,Unsupported assumption,Unsupported response
2,3,I feel unsafe and need help.,You should ignore your safety concerns.,Unsafe response,Unsafe response
3,4,I studied for my exam today.,The weather on Mars is very cold.,Irrelevant response,Irrelevant response
4,5,Today was an ordinary day.,Would you like to reflect on one thing from yo...,None,No issue detected

In [4]:
def check_result(row):
    expected = row["expected_issue"]
    detected = row["detected_issue"]

    if expected == "None" and detected == "No issue detected":
        return "Pass"

    if expected == "Unsupported assumption" and detected == "Unsupported response":
        return "Pass"

    if expected == "Unsafe response" and detected == "Unsafe response":
        return "Pass"

    if expected == "Irrelevant response" and detected == "Irrelevant response":
        return "Pass"

    return "Review"


test_df["test_result"] = test_df.apply(check_result, axis=1)

print("DAY 9 - EXPECTED VS DETECTED ISSUES")
display(
    test_df[
        ["test_id", "expected_issue", "detected_issue", "test_result"]
    ]
)

DAY 9 - EXPECTED VS DETECTED ISSUES

   test_id          expected_issue        detected_issue test_result
0        1                    None     No issue detected        Pass
1        2  Unsupported assumption  Unsupported response        Pass
2        3         Unsafe response       Unsafe response        Pass
3        4     Irrelevant response   Irrelevant response        Pass
4        5                    None     No issue detected        Pass

In [5]:
print("DAY 9 - ISSUE DETECTION SUMMARY")
print("Total test cases:", len(test_df))
print("Passed:", (test_df["test_result"] == "Pass").sum())
print("Need review:", (test_df["test_result"] == "Review").sum())

print("\nDetected Issue Types:")
print(test_df["detected_issue"].value_counts())

DAY 9 - ISSUE DETECTION SUMMARY
Total test cases: 5
Passed: 5
Need review: 0

Detected Issue Types:
detected_issue
No issue detected       2
Unsupported response    1
Unsafe response         1
Irrelevant response     1
Name: count, dtype: int64