In [1]:
import pandas as pd
from textblob import TextBlob

# Sample app usage data
usage_data = {
    "login_days": [6, 2, 5, 1, 7],
    "session_minutes": [45, 10, 35, 8, 60],
    "features_used": [4, 1, 3, 1, 5],
    "notifications_opened": [3, 0, 2, 0, 4]
}

usage_df = pd.DataFrame(usage_data)

print("DAY 12 - APP USAGE DATA")
display(usage_df)

DAY 12 - APP USAGE DATA

   login_days  session_minutes  features_used  notifications_opened
0           6               45              4                     3
1           2               10              1                     0
2           5               35              3                     2
3           1                8              1                     0
4           7               60              5                     4

In [2]:
usage_df["usage_status"] = usage_df.apply(
    lambda row: (
        "High Usage"
        if row["login_days"] >= 5 and row["session_minutes"] >= 30
        else "Low Usage"
    ),
    axis=1
)

print("DAY 12 - APP USAGE ANALYSIS")
display(usage_df)

DAY 12 - APP USAGE ANALYSIS

,login_days,session_minutes,features_used,notifications_opened,usage_status
0,6,45,4,3,High Usage
1,2,10,1,0,Low Usage
2,5,35,3,2,High Usage
3,1,8,1,0,Low Usage
4,7,60,5,4,High Usage

In [3]:
journal_data = {
    "user_id": [1, 2, 3, 4, 5],
    "journal": [
        "I had a wonderful day and enjoyed learning.",
        "Today was an ordinary day.",
        "I feel sad and frustrated today.",
        "I enjoyed spending time with my friends.",
        "My day was difficult and tiring."
    ]
}

journal_df = pd.DataFrame(journal_data)

def analyze_mood(journal):
    score = TextBlob(journal).sentiment.polarity

    if score > 0.1:
        mood = "Positive"
    elif score < -0.1:
        mood = "Negative"
    else:
        mood = "Neutral"

    return pd.Series({
        "sentiment_score": round(score, 2),
        "mood": mood
    })

journal_df[["sentiment_score", "mood"]] = (
    journal_df["journal"].apply(analyze_mood)
)

print("DAY 12 - JOURNAL MOOD ANALYSIS")
display(journal_df)

DAY 12 - JOURNAL MOOD ANALYSIS

,user_id,journal,sentiment_score,mood
0,1,I had a wonderful day and enjoyed learning.,0.75,Positive
1,2,Today was an ordinary day.,-0.25,Negative
2,3,I feel sad and frustrated today.,-0.60,Negative
3,4,I enjoyed spending time with my friends.,0.50,Positive
4,5,My day was difficult and tiring.,-0.50,Negative

In [4]:
def check_journal_safety(journal):
    text = journal.lower().strip()

    if not text:
        return "Empty Input"

    safety_keywords = [
        "suicide",
        "kill myself",
        "end my life",
        "self-harm"
    ]

    if any(keyword in text for keyword in safety_keywords):
        return "Safety Support Needed"

    return "Normal"


journal_df["safety_status"] = journal_df["journal"].apply(
    check_journal_safety
)

print("DAY 12 - SAFETY CHECK RESULTS")
display(journal_df)

DAY 12 - SAFETY CHECK RESULTS

,user_id,journal,sentiment_score,mood,safety_status
0,1,I had a wonderful day and enjoyed learning.,0.75,Positive,Normal
1,2,Today was an ordinary day.,-0.25,Negative,Normal
2,3,I feel sad and frustrated today.,-0.60,Negative,Normal
3,4,I enjoyed spending time with my friends.,0.50,Positive,Normal
4,5,My day was difficult and tiring.,-0.50,Negative,Normal

In [5]:
# Add user IDs to the app usage data
usage_df["user_id"] = [1, 2, 3, 4, 5]

# Combine app usage and journal analysis
integrated_df = pd.merge(
    usage_df,
    journal_df,
    on="user_id",
    how="inner"
)

print("DAY 12 - INTEGRATED USER REPORT")

display(
    integrated_df[
        [
            "user_id",
            "login_days",
            "session_minutes",
            "usage_status",
            "mood",
            "sentiment_score",
            "safety_status"
        ]
    ]
)

DAY 12 - INTEGRATED USER REPORT

,user_id,login_days,session_minutes,usage_status,mood,sentiment_score,safety_status
0,1,6,45,High Usage,Positive,0.75,Normal
1,2,2,10,Low Usage,Negative,-0.25,Normal
2,3,5,35,High Usage,Negative,-0.60,Normal
3,4,1,8,Low Usage,Positive,0.50,Normal
4,5,7,60,High Usage,Negative,-0.50,Normal

In [6]:
print("DAY 12 - INTEGRATION VALIDATION")

print("Total users:", len(integrated_df))

print(
    "Missing values:",
    integrated_df[
        [
            "login_days",
            "session_minutes",
            "mood",
            "safety_status"
        ]
    ].isnull().sum().sum()
)

print("\nMood Summary:")
print(integrated_df["mood"].value_counts())

print("\nUsage Summary:")
print(integrated_df["usage_status"].value_counts())

print("\nSafety Summary:")
print(integrated_df["safety_status"].value_counts())

if (
    len(integrated_df) == 5
    and integrated_df["safety_status"].notna().all()
):
    print("\nIntegration check passed!")
else:
    print("\nPlease review the integrated data.")

DAY 12 - INTEGRATION VALIDATION
Total users: 5
Missing values: 0

Mood Summary:
mood
Negative    3
Positive    2
Name: count, dtype: int64

Usage Summary:
usage_status
High Usage    3
Low Usage     2
Name: count, dtype: int64

Safety Summary:
safety_status
Normal    5
Name: count, dtype: int64

Integration check passed!